name: Build and Publish Docker Image

on:
  release:
    types: [published]
  push:
    branches: ["main"]

env:
  IMAGE_NAME: coolplaylin-bot

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        REGISTRY: [docker.io, ghcr.io]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry - DockerHub
        if: matrix.REGISTRY == 'docker.io'
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log into registry - Github
        if: matrix.REGISTRY == 'ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract Docker metadata - DockerHub
        if: matrix.REGISTRY == 'docker.io'
        id: meta-dockerhub
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}
      
      - name: Extract Docker metadata - Github
        if: matrix.REGISTRY == 'ghcr.io'
        id: meta-github
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image - DockerHub
        if: matrix.REGISTRY == 'docker.io'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-dockerhub.outputs.tags }}
          labels: ${{ steps.meta-dockerhub.outputs.labels }}

      - name: Build and push Docker image - Github
        if: matrix.REGISTRY == 'ghcr.io'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-github.outputs.tags }}
          labels: ${{ steps.meta-github.outputs.labels }}